GRANT ALL PRIVILEGES ON *.* TO 'miconnect'@'localhost' IDENTIFIED BY PASSWORD '*6BB4837EB74329105EE4568DDA7DC67ED2CA2AD9' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON `miconnect`.* TO 'miconnect'@'localhost' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON `miconnect\_%`.* TO 'miconnect'@'localhost';